### PR TITLE
Create `spaceflights-pyspark-viz`

### PR DESCRIPTION
**Pull request by merelcht**
## Motivation and Context

Subtask of https://github.com/kedro-org/kedro/issues/2838

Spaceflights pyspark with Kedro-Viz features enabled:
- Matplotlib
- Ploty
- Experiment Tracking

## How has this been tested?
Created a project locally using: `kedro new --starter=/Users/merel_theisen/Projects/kedro-starters/spaceflights-pyspark-viz/` and did `kedro run`

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Assigned myself to the PR
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by ankatiyar — COMMENTED** [review]
I tested the starter with `kedro new --starter` and `kedro run` and it works!

I do have a question - are these `__init__.py` files needed? 
- spaceflights-pyspark-viz/__init__.py
- spaceflights-pyspark-viz/{{ cookiecutter.repo_name }}/__init__.py
- spaceflights-pyspark-viz/{{ cookiecutter.repo_name }}/src/__init__.py
Didn't see them in the current spaceflights or #147

**Review by SajidAlamQB — APPROVED** [review]
I've tested it manually and looked it over all seems good. 👍

**Comment by merelcht** [comment]
> I do have a question - are these `__init__.py` files needed?
> 
> * spaceflights-pyspark-viz/**init**.py
> * spaceflights-pyspark-viz/{{ cookiecutter.repo_name }}/**init**.py
> * spaceflights-pyspark-viz/{{ cookiecutter.repo_name }}/src/**init**.py
>   Didn't see them in the current spaceflights or [Add `spaceflights-pyspark` starter #147](https://github.com/kedro-org/kedro-starters/pull/147)

Good spot! I think my IDE added those automatically.

**Review by ankatiyar — APPROVED** [review]
Looks good to me! 💯

**Pull request merged**
