### PR TITLE
Update catalog for namespace pref

### PR DESCRIPTION
**Pull request by avan-sh**
## Motivation and Context

Addresses #80 to update prefixes to the catalog

## How has this been tested?
Ensure no datasets come under `Datasets not mentioned in pipeline:`
image

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Assigned myself to the PR
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by AntonyMilneQB — APPROVED** [review]
Thanks so much for doing this @avan-sh. Would you mind updating the spaceflights tutorial in the documentation to make sure it matches?

**Review by noklam — APPROVED** [review]
Thank @avan-sh for making this fix! 🎉

@AntonyMilneQB Seeing this just get me thinking why do we have indentation for namespace for parameters but "dot" syntax for datasets? Seems a bit inconsistent.

**Comment by noklam** [comment]
But for dataset, only the `dot` syntax would work, not the top-level key right?

**Comment by noklam** [comment]
Thank you! The context is very helpful to understand the  evolution of the design.

**Pull request merged**
