### PR TITLE
Add python 3.12 to starters builds

### PR DESCRIPTION
**Pull request by ankatiyar**
## Motivation and Context

Noticed that 3.12 builds were missing!
## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Assigned myself to the PR
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by noklam — APPROVED** [review]
Good catch

**Comment by ankatiyar** [comment]
`distutils` removed in Python 3.12 🤔

**Comment by ElenaKhaustova** [comment]
> `distutils` removed in Python 3.12 🤔

Yeah, https://docs.python.org/3.12/whatsnew/3.12.html#distutils

**Comment by ankatiyar** [comment]
* They've fixed it on `pyspark` but it'll only be out in 4.0.0 https://issues.apache.org/jira/browse/SPARK-45390
* A solution I saw was installing `setuptools` 🤔

**Comment by ankatiyar** [comment]
Adding `setuptools` to the requirements.txt for `spaceflights-pandas-viz` for python 3.12 does solve the issue but the `tools.feature` test will fail still because it pulls the last released version of starters.
Here's what we can do -
* Separate PR for adding `setuptools` to the `requirements.txt` will only run tests till 3.11 so can be merged
* Delete and re-tag 0.19.5 on starters
* Then add "3.12" to the builds 

What do you think @ElenaKhaustova @astrojuanlu @noklam?
Or we could wait till `pyspark` 4.0.0 comes out.
We have already added support for python 3.12 in the last release on Kedro, this should technically have been a part of 0.19.4

**Comment by noklam** [comment]
Is this a build or project requirements? Usually `setuptools` is a [build](https://github.com/kedro-org/kedro/blob/ef34c9b68e1a983b6463a4603f630aa18744fd68/pyproject.toml#L2-L5) requirements and we tried very hard in the past to remove it from `kedro` library depedencies (it's big and slow, used for micropkg)

**Comment by ankatiyar** [comment]
@noklam just adding it to the `requirements.txt` for the `spaceflights-pyspark-viz` starter (only if `python_version>3.11`)
https://stackoverflow.com/questions/77233855/why-did-i-got-an-error-modulenotfounderror-no-module-named-distutils
Wouldn't need it after `pyspark` releases 4.0.0

**Comment by noklam** [comment]
After reading the JIRA issue, I think it's okay to included it in requirements.txt conditionally for >=3.12. It's a shame PySpark didn't support this. We should leave a comment in the requirements too.

**Comment by ankatiyar** [comment]
All done! ✅

**Review by ElenaKhaustova — APPROVED** [review]

**Review by SajidAlamQB — APPROVED** [review]

**Pull request merged**
