### PR TITLE
Add Apache 2.0 LICENSE.md file 

### PR DESCRIPTION
**Pull request by datajoely**
## Motivation and Context
An open source user correctly identified that we don't include a LICENSE.md in this repository [#1222](https://github.com/kedro-org/kedro/discussions/1222) as an LFAI project all repositories under `kedro-org` should be Apache 2.0

## How has this been tested?
Not required

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Assigned myself to the PR
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by yetudada — APPROVED** [review]
Thanks for flagging this 🚀

**Comment by datajoely** [comment]
Thanks @simkimsia!

**Review by lorenabalan — APPROVED** [review]

**Comment by datajoely** [comment]
@lorenabalan  I'm not sure why E2E give me a `kedro.pipeline.modular_pipeline.ModularPipelineError: Failed to map datasets and/or parameters: params:model_options` I've cloned locally and it works. Is there a mismatch between release tags?

**Comment by lorenabalan** [comment]
Seems that the problem resolved itself after merging latest `main`.

**Pull request merged**
