### PR TITLE
Feature/reduce spaceflights data

### PR DESCRIPTION
**Pull request by laizaparizotto**
## Motivation and Context
This PR tackles the enhancement proposed by @merelcht at https://github.com/kedro-org/kedro/issues/3109 to reduce spaceflights data:

> [The spaceflights starter](https://github.com/kedro-org/kedro-starters/tree/main/spaceflights) gets used in demos and testing, it takes a considerate of time to run the pipeline. For example in the Kedro bootcamp demoing catalog.load("shuttles") takes like 15-20 seconds and is a bit awkward for demo purpose.

**What was done to reduce data:**

1. Dropped duplicates from `companies`
    - _Before = 77096 rows_ -> _after = 50098 rows_

2. Randomly split `companies`, keeping 20%.
    - _Before = 50098 unique `id` -> after= 10019 unique `id`_
 
3. Keep only `shuttles` where `shuttles.company_id.isin(companies.id.unique())`
4. Keep only `reviews` where `reviews.shuttle_id.isin(new_shuttles.id.unique())`

**Adaptation at src code:**
- I removed the `drop_duplicates` from `companies` in the `data_processing` node `create_model_input_table`.

## How has this been tested?
**First test**: loading data in `kedro ipython` using `catalog.load("shuttles")`
- Data is loaded in **3-5 seconds.**

**Second test**: running the entire pipeline with `kedro run`
```
[10/29/23 09:43:09] INFO     Kedro project spaceflights                                                                                       session.py:365
[10/29/23 09:43:11] INFO     Loading data from 'companies' (CSVDataset)...                                                               data_catalog.py:502
                    INFO     Running node: preprocess_companies_node: preprocess_companies([companies]) -> [preprocessed_companies]              node.py:331
                    INFO     Saving data to 'preprocessed_companies' (ParquetDataset)...                                                 data_catalog.py:541
                    INFO     Completed 1 out of 6 tasks                                                                              sequential_runner.py:85
                    INFO     Loading data from 'shuttles' (ExcelDataset)...                                                              data_catalog.py:502
[10/29/23 09:43:15] INFO     Running node: preprocess_shuttles_node: preprocess_shuttles([shuttles]) -> [preprocessed_shuttles]                  node.py:331

[...]

                    INFO     Model has a coefficient R^2 of 0.402 on test data.                                                                  nodes.py:55
                    INFO     Completed 6 out of 6 tasks                                                                              sequential_runner.py:85
                    INFO     Pipeline execution completed successfully.                                                                        runner.py:105
```

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Assigned myself to the PR
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by noklam** [comment]
I don't mind a more aggressive trim that the whole pipeline can be run within 2 seconds. In general the approach is fine because it is mainly for demo purpose. However, I think we can do better here to create an more realistic example.

> -  I randomly split the data companies, reviews and shuttles.
> -  40% of total data was kept.
> - Replaced the files in the repository

Randomly drop the three files individually will create data that couldn't be joined. A more realistic approach is drop X % of company data, and remove all relevant entries in the review and shuttles data. WDYT?

**Comment by laizaparizotto** [comment]
Hi @noklam, thank you for the feedback.

I agree with you, randomly splitting may generate some inconsistency in the data, I see it now. 

***
What I still don't understand is why `companies` and `shuttles` have the same size in first place? The values for companies are repeated (and unique), meaning that it should be more like a dimension table, right?

i.e. when we have a company id being repeated many times, it also happens in shuttles data:

This is `shuttles.csv`
| id   | shuttle_location | shuttle_type | engine_type | engine_vendor        | engines | passenger_capacity | cancellation_policy | crew | d_check_complete | moon_clearance_complete | price     | company_id |
| ---- | ---------------- | ------------ | ----------- | -------------------- | ------- | ------------------ | ------------------- | ---- | ---------------- | ---------------------- | --------- | ----------  |
| 65,070 | Malta         | Type V2     | Plasma     | ThetaBase Services   | 5      | 8                | strict              | 8    | f                | f                     | $3,665.0  | 50,072     |
| 12,631 | Malta         | Type V2     | Quantum    | ThetaBase Services   | 1      | 2                | flexible            | 1    | t                | f                     | $1,403.0  | 50,072     |
| 2,138  | Malta         | Type F5     | Quantum    | ThetaBase Services   | 1      | 1                | flexible            | 1    | t                | f                     | $1,221.0  | 50,072     |



This is `companies.csv`

| Id    | Company_rating | Company_location  | Total_fleet_count | lata_approved |
| ----  | -------------- | ------------------ | ------------------ | -------------  |
| 50072 | 100%           | Marshall Islands   | 3                 | t             |
| 50072 | 100%           | Marshall Islands   | 3                 | t             |
| 50072 | 100%           | Marshall Islands   | 3                 | t             |





***

But, what I would propose then, is to **cut by a company `id` value.** There are `50098` unique values for `company_id` and we could cut it at `20000` or whatever value you propose.

What do you think?

**Comment by noklam** [comment]
@laizaparizotto  Thanks. I notice that there is a [new change](https://github.com/kedro-org/kedro-starters/pull/154/files) recently to drop duplicate. IMO, the company data shouldn't be duplicated (Or we can have it duplicate and de-duplicate in the `preprocess_companies` to showcase some data engineering step).

I prefer the former one just for simplicity. We will also need to update all the data because we have a few more starters. https://github.com/kedro-org/kedro-starters, we need to have consistent data and pipeline across all `spaceflights-xxx` starers as well. 

p.s. In 0.19 we will remove other starters and keep the `spaceflights-xxx`.

Cc @merelcht

**Comment by merelcht** [comment]
I agree with you @noklam I don't think the de-duplication is particularly interesting in the example and ideally we wouldn't have any duplicates to start with especially if that reduces the data already.

**Comment by merelcht** [comment]
Hi @laizaparizotto, how is it going with this task? Do you need some help?

**Comment by laizaparizotto** [comment]
Hi @merelcht, I will get back to it this weekend. Thanks for the messsage.

**Comment by laizaparizotto** [comment]
Hi guys.

I just updated the PR description with the new changes. There I explained the process to reduce the data considering the discussing from the comments here.

> I prefer the former one just for simplicity. We will also need to update all the data because we have a few more starters. https://github.com/kedro-org/kedro-starters, we need to have consistent data and pipeline across all spaceflights-xxx starers as well.

Then, @noklam and @merelcht if you think these changes are okay, I also push the files to the other directories  `spaceflights-xxx`

**Comment by merelcht** [comment]
This approach looks good to me thanks @laizaparizotto 🙂 @noklam are you also okay with keeping only the 20% of the data?

**Comment by noklam** [comment]
Thanks @laizaparizotto , I am fine with the changes.

**Comment by laizaparizotto** [comment]
Okay, great. I just updated the files in the other directories.

I will open the PR at `kedro` as well.

**Review by merelcht — APPROVED** [review]
Thanks so much for this contribution @laizaparizotto 👍 ⭐

**Comment by merelcht** [comment]
> Okay, great. I just updated the files in the other directories.
> 
> I will open the PR at `kedro` as well. @stichbury There the PR should be addressed to `develop` or to `main`?

IMO this can go on `main`, because it's just test data. Nobody should be relying on this data.

**Comment by stichbury** [comment]
Agreed, this can go onto `main`. Do we reproduce this data anywhere else?

**Comment by laizaparizotto** [comment]
I also only found the files there @noklam

**Review by noklam — APPROVED** [review]

**Pull request merged**
