### PR TITLE
Relax the upper bound on `jupyter_client` :arrow_up:

### LINKED ISSUE #72: Annoyingly I think we need to do the same thing in the starters repo 🙈
Annoyingly I think we need to do the same thing in the starters repo 🙈 
https://github.com/kedro-org/kedro-starters/blob/1559a2a4750caed6d98c7e880bec70b5c71b43d4/astro-airflow-iris/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/requirements.txt

_Originally posted by @datajoely in https://github.com/kedro-org/kedro/issues/1322#issuecomment-1061970958_

### PR DESCRIPTION
**Pull request by deepyaman**
## Motivation and Context

Closes #72 

## Checklist

- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Assigned myself to the PR
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by deepyaman** [comment]
FYI @datajoely

**Comment by datajoely** [comment]
Oh you star! Thank you!

**Review by AntonyMilneQB — APPROVED** [review]

**Comment by AntonyMilneQB** [comment]
Oh, I just noticed this isn't running the CI checks. Please could you do whatever you did to fix your kedro forks CircleCI issue here also?

**Comment by lorenabalan** [comment]
Looks like the astro-iris starter is unhappy, happy to approve once it's fixed. Also please remember to sign off every commit in order for the DCO plugin to pass (we can force it to pass but it's not sustainable in the long term). We know it's not an ideal workflow but it'a a requirements from Linux Foundation. You can have a look at https://github.com/kedro-org/kedro/blob/main/Makefile#L59-L63 for shortcut on how we enable it by default for `kedro`.

**Comment by lorenabalan** [comment]
Closing this as it will be removed altogether in https://github.com/kedro-org/kedro-starters/pull/78

**Pull request closed without merging**
