### PR TITLE
0.18.0 Changes

### PR DESCRIPTION
**Pull request by lorenabalan**
Signed-off-by: lorenabalan <lorena.balan@quantumblack.com>

## Motivation and Context

To make the release easier to navigate, I'm incorporating all changes for 0.18 in one branch / PR:
* [#55](https://github.com/kedro-org/kedro-starters/pull/55) ➡️  Reverts quantumblacklabs/kedro-starters#49. In kedro 0.18 , `openpyxl` is the default and will be installed through `kedro[pandas.ExcelDataSet]`.
* [#37](https://github.com/kedro-org/kedro-starters/pull/37) ➡️  Rename `mini-kedro` to `standalone-datacatalog`.
* [#68](https://github.com/kedro-org/kedro-starters/pull/68) ➡️  General cleanup to sync up starters with project template; see [PR description](https://github.com/kedro-org/kedro-starters/pull/68#issue-1158482476) for details.
* https://github.com/kedro-org/kedro-starters/pull/69/commits/34ef44d06cccc2c1bccbe378557bc75576fe34ff ➡️   Removed `wheel` from project requirements; follow-up to https://github.com/kedro-org/kedro/pull/1305
* https://github.com/kedro-org/kedro-starters/pull/69/commits/197e0dcaa18c2ca1ffa4fefccf1dca858d8a59a3 ➡️  Make it easier for people to run Kedro projects by simply importing them; follow-up to https://github.com/kedro-org/kedro/pull/1364
* https://github.com/kedro-org/kedro-starters/pull/78 ➡️  Remove .ipython dir and update readme files
* https://github.com/kedro-org/kedro-starters/pull/77 ➡️  Make `black` requirement consistent with core Kedro & remove click requirement

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Assigned myself to the PR
- [ ] Added tests to cover my changes

### CODE REVIEW

**Comment by AntonyMilneQB** [comment]
Just to check I understand the scheme... Is this what we're planning to do?
1. point this branch to `kedro@develop` just for CI testing purposes
2. release kedro 0.18
3. revert this branch to `kedro@main`
4. merge this branch

**Comment by lorenabalan** [comment]
> Just to check I understand the scheme... Is this what we're planning to do?

Yes something like that but _please_ be patient and bear with me, I was going to update the release checklist with the concrete steps as well. This is my proposal, no official agreement.

**Comment by AntonyMilneQB** [comment]
I think we're going to need to update the pyspark `ProjectContext` to reflex the new `KedroContext` signature.

**Comment by MerelTheisenQB** [comment]
> I think we're going to need to update the pyspark `ProjectContext` to reflex the new `KedroContext` signature.

Yes good point!

**Review by AntonyMilneQB — APPROVED** [review]

**Review by noklam — APPROVED** [review]

**Pull request merged**
