### PR TITLE
Update kedro-datasets optional dependencies requirements naming

### PR DESCRIPTION
**Pull request by lrcouto**
## Motivation and Context

Part of the proposal for https://github.com/kedro-org/kedro-plugins/issues/313. To be merged after `kedro-datasets 3.0.0` release. Updates the requirements for starters to use the new naming convention for `kedro-datasets` optional dependencies.

Depends on https://github.com/kedro-org/kedro-plugins/pull/570

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Assigned myself to the PR
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by astrojuanlu — COMMENTED** [review]
:100:

**Comment by lrcouto** [comment]
Tests are expected to fail until the `kedro-datasets 3.0.0` release.

**Review by ElenaKhaustova — APPROVED** [review]
Tested updated datasets' names

All tests are passing when pointing test branch: https://github.com/kedro-org/kedro/compare/main...debug/point-to-test-starters-branch

Reverted back to point to `main` branch, so tests failing is expected

**Review by merelcht — APPROVED** [review]
LGTM! 👍

**Pull request merged**
