### PR TITLE
More flexible pinning of Jupyter optional dependencies

### PR DESCRIPTION
**Pull request by astrojuanlu**
See https://github.com/kedro-org/kedro/issues/2276 and https://github.com/kedro-org/kedro/pull/3288/

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [ ] Assigned myself to the PR
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by merelcht — APPROVED** [review]
🥳

**Review by noklam — APPROVED** [review]

**Comment by astrojuanlu** [comment]
pip doing some heavy backtracking on kedro-datasets:

```
WARNING: kedro-datasets 1.8.0 does not provide the extra 'hdfs-base'
WARNING: kedro-datasets 1.8.0 does not provide the extra 's3fs-base'
WARNING: kedro-datasets 1.8.0 does not provide the extra 'spark-base'
```

**Comment by noklam** [comment]
revert a few commits, changed made in a separate PR #201.

**Comment by noklam** [comment]
The issue was fixed separate in #201

**Pull request merged**
