### PR TITLE
Make all starters use pyproject.toml

### PR DESCRIPTION
**Pull request by DimedS**
## Motivation and Context
This PR builds upon the approach outlined in [#2583](https://github.com/kedro-org/kedro/pull/2853). Initially, we transition from `setup.py` to `pyproject.toml`, keeping them at the same level within the '/src' folder. Concurrently, we shift from `setup.cfg` to the `.flake8` configuration files. In the subsequent phase, with the release of Kedro 0.19, we plan to move `pyproject.toml `up one directory level and merge it with the existing `pyproject.toml` file.

## How has this been tested?
Tested manually:
`kedro new --starter git+https://github.com/kedro-org/kedro-starters.git --directory spaceflights --checkout 2280-make-all-starters-use-pyprojecttoml`

## Checklist

- [x] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [x] Assigned myself to the PR
- [ ] Added tests to cover my changes

### CODE REVIEW

**Review by astrojuanlu — COMMENTED** [review]
Gave a quick first inspection, all `pyproject.toml` files are lacking a final newline

**Comment by DimedS** [comment]
> Gave a quick first inspection, all `pyproject.toml` files are lacking a final newline

thanks, fixed it!

**Comment by astrojuanlu** [comment]
3.10 jobs failing because of using an old PyYAML, see https://github.com/yaml/pyyaml/issues/601#issuecomment-1639515421

we'd either have to bump the PyYAML dependency, or constrain Cython<3 in the build phase.

**Comment by DimedS** [comment]
> 3.10 jobs failing because of using an old PyYAML, see [yaml/pyyaml#601 (comment)](https://github.com/yaml/pyyaml/issues/601#issuecomment-1639515421)
> 
> we'd either have to bump the PyYAML dependency, or constrain Cython<3 in the build phase.

@astrojuanlu, thank you for pointing that out. It indeed seems to be an issue with Python 3.10. Can you clarify who and why installed Cython in that case? Regardless, it might be a good idea to update our PyYAML requirements to match Kedro's: "PyYAML>=4.2, <7.0". Do you foresee any issues with this adjustment?"

**Review by noklam — APPROVED** [review]
Looks good to me, I didn't test because CI is passing.

**Comment by astrojuanlu** [comment]
I think it's good that we move to the new PyYAML, thanks @DimedS !

**Review by astrojuanlu — APPROVED** [review]
This and https://github.com/kedro-org/kedro/pull/2853 are ready to be merged 🔥

**Pull request merged**
